:imagesdir: img

:sectnums!:
= Аннотация

Руководство пользователя описывает работу с программным обеспечением (ПО) автоматизированного рабочего места информационной безопасности (АРМ ИБ) ПК «Аркан».
Настоящее руководство предназначено для технических специалистов и пользователей и содержит условия и правила запуска и остановки ПО, описание диалога с оператором и сообщения оператору.
Пользователь ПО АРМ ИБ ПК «Аркан» должен изучить настоящее руководство и иную эксплуатационную документацию.
ПО АРМ ИБ ПК «Аркан» используется для управления продуктами ПАК «Аркан-М» и ПАК «Аркан-К». При этом предоставляется единый унифицированный интерфейс.
Пользовательский интерфейс подключается либо к ПАК «Аркан-М» и позволяет управлять им, либо к ПАК «Аркан-К». В зависимости от этого системные настройки будут позволять управление тем устройством, к которому произведено подключение.
Программный комплекс «Аркан» функционально состоит из модуля устройства защиты и сервера. В данном руководстве описан интерфейс ПК «Аркан».
На основе ПК «Аркан» функционируют два продукта ПАК «Аркан-М» (где совмещены оба модуля ПК «Аркан») и ПАК «Аркан-К» (вынесенный на отдельное устройство модуль сервера).

:sectnums:

<<<<
